apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goat-client
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goat-client
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: goat-client
    spec:
      containers:
        - image: docker.io/goatcommunity/api:3d48b7bd2a14000b83529778763de203cff21ac8
          imagePullPolicy: IfNotPresent
          name: goat-client
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 512Mi
              cpu: 200m
            limits:
              memory: 1Gi
              cpu: 300m
          env:
            - name: VUE_APP_I18N_LOCALE
              value: en
            - name: VUE_APP_I18N_FALLBACK_LOCALE
              value: en
            - name: VUE_APP_SEARCH_KEY
              value: ca068d7840bca4
            - name: VUE_APP_SEARCH_URL
              value: https://api.locationiq.com/v1/autocomplete.php
            - name: API_BASEURL
              value: https://demo.open-accessibility.org/api/
            - name: GEOSERVER_BASEURL
              value: https://demo.open-accessibility.org/geoserver/
            - name: PRINT_URL
              value: https://demo.open-accessibility.org/print/
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: goat-client
  namespace: development
spec:
  rules:
    - host: demo.open-accessibility.org
      http:
        paths:
          - backend:
              serviceName: goat-client
              servicePort: 80
            path: /
  tls:
    - hosts:
        - demo.open-accessibility.org
      secretName: letsencrypt-prod
---
apiVersion: v1
kind: Service
metadata:
  name: goat-client
  namespace: development
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: goat-client
